# Generated by Django 6.0.7 on 2026-09-06 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ncrb_auth', '0002_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('fir_number', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('case_type', models.CharField(choices=[('CRIMINAL', 'Criminal'), ('CIVIL', 'Civil'), ('INVESTIGATION', 'Investigation')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CHARGESHEETED', 'Chargesheeted'), ('IN_TRIAL', 'In Trial'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('opened_date', models.DateField(auto_now_add=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='ncrb_auth.organization')),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case_number', 'status'], name='cases_case_nu_bc9c0a_idx'), models.Index(fields=['assigned_officer', 'status'], name='cases_assigne_b0271c_idx'), models.Index(fields=['organization', 'status'], name='cases_organiz_825e54_idx')],
            },
        ),
    ]
