# Generated by Django 6.1.1 on 2026-09-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_hash', models.CharField(db_index=True, max_length=64)),
                ('blockchain_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='confirmed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blockchain_record', to='documents.documentversion')),
            ],
        ),
    ]
