# Generated by Django 5.2.11 on 2026-09-06 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_code', models.CharField(max_length=30)),
                ('org_name', models.CharField(max_length=150)),
                ('org_type', models.CharField(choices=[('POLICE_STATION', 'Police Station'), ('COURT', 'Court'), ('NCRB', 'NCRB'), ('FORENSIC_LAB', 'Forensic Lab'), ('LEGAL_DEPT', 'Legal Department')], max_length=20)),
                ('jurisdiction_code', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('district', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret_encrypted', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=20)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='ncrb_auth.organization')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
