# Generated by Django 6.0.7 on 2026-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncrb_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('OFFICER', 'Officer'), ('JUDGE', 'Judge'), ('CLERK', 'Clerk'), ('FORENSIC', 'Forensic'), ('AUDITOR', 'Auditor')], default='OFFICER', max_length=20),
        ),
    ]
